'use strict';

require('angular')
	.module('app', [
		// html templates in $templateCache generated by Gulp:
		require('../tmp/templates').name,
		require('./core/core.module').name,
		require('./layout/layout.module').name
	]);